### ISSUE TITLE
URL was changed?

### ISSUE THREAD

**Issue by ses4j** [Zoziologie/e2L#1]
Came across your script/website.  Just what I wanted, but I tried to use it and got this:

```
code_loc=DO-11&project_name=La+Altagracia&byear=2007&eyear=2017&bmonth=01&emonth=12&cat=species&cat=spuh&cat=slash&cat=hybrid&cat=domestic&cat=issf&cat=intergrade&cat=form&col=note,4cm,0&col=checkbox,1,0&col=hyphen,1,1ex&col=lang,EN,0&col=freq,year,0&condition=0.1&condition=0.01&format=a4paper,margin=0.3in&family=false
1. Read the url, transform it to dict and adapt it for our purpuse
{'code_loc': ['DO-11'], 'project_name': ['La Altagracia'], 'bmonth': ['01'], 'family': ['false'], 'format': ['a4paper,margin=0.3in'], 'eyear': ['2017'], 'byear': ['2007'], 'emonth': ['12'], 'cat': ['species', 'spuh', 'slash', 'hybrid', 'domestic', 'issf', 'intergrade', 'form'], 'col': ['note,4cm,0', 'checkbox,1,0', 'hyphen,1,1ex', 'lang,EN,0', 'freq,year,0'], 'condition': ['0.1', '0.01']}
2. Create the Bird List from eBird.org
barchar url: 
http://ebird.org/ebird/BarChart?cmd=getChart&displayType=download&reportType=location&getLocations=states&states=DO-11&bYear=2007&eYear=2017&bMonth=1&eMonth=12
The python script has fail. Sorry for this. Would you mind reporting the error to rafnuss@gmail.com. Thanks

Error Traceback:
Traceback (most recent call last):
  File "script_web_e2L.py", line 32, in 
    info, bird_list = e2L.bird_creator(code_loc, lang, cat, byear, eyear, bmonth, emonth)
  File "/var/www/zoziologie/wp-content/plugins/e2L/e2L.py", line 73, in bird_creator
    bc_bird_list, info = load_barchart(code_loc, byear, eyear, bmonth, emonth)
  File "/var/www/zoziologie/wp-content/plugins/e2L/e2L.py", line 108, in load_barchart
    lines = urllib.request.urlopen(url).readlines()
  File "/usr/lib/python3.2/urllib/request.py", line 139, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.2/urllib/request.py", line 376, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 488, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 414, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 348, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 496, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by ses4j** [comment]
It looks like the new url should be:

	url = 'http://ebird.org/ebird/barchartData?r={code_loc}&bmo={bmonth}&emo={emonth}&byr={byear}&eyr={eyear}&fmt=tsv'.format(
		code_loc=code_loc, byear=byear, eyear=eyear, bmonth=bmonth, emonth=emonth)

**Comment by ses4j** [comment]
Actually made a few changes - the download wasn't working right because it didn't follow redirects, so I switched in the `requests` module which does it more easily.  Also a few other random changes.  Here's my commit:

https://github.com/ses4j/e2L/commit/3c5e882f097d0012e389b3ec1f727afb171f04f4

I can make a pull request if you're interested.

**Comment by ses4j** [comment]
Oh, and love the script!  I got great results once I waded in... All ready for my upcoming trip!

[DominicanRepublic.pdf](https://github.com/Zoziologie/e2L/files/884442/DominicanRepublic.pdf)

**Comment by Rafnuss** [comment]
Hey @ses4j , thanks for that! Look much better. Can you make a pull request?
